$ANSIBLE_VAULT;1.1;AES256
62663730643239663661316331616462636136333265316163323431356333313538353762356565
3538643932393738323964363534646263393839393133360a336538363239393364626232633331
61313764396331373539346239363433653462396262313436393434613261346330653366343931
3437663336306364300a636533343339666262336362643439666264653665626137323763623032
37613337373564343136653731313733633366326265353162363738326231343433636635623530
39383834303365346663323663383665366162353764353831653461663637643731316430343565
65376637376232366364313135336466653463643531613039386361306564353633396633306637
63373638306264323862396566616637653366333961623461303735333538383730653033333463
66363538316433396330346463303431633031646536343437326431333363656533636332366466
39326638393130626662356135663263383161653632636139376166646332633530653564363932
64636262373866653733383137313733383639393937663035336565393936666434666464643234
65626536656338336334373637393136663039626537623238616264636332633433363262373965
63626237306466656333343835343333616463343565346262626462323161656334383366323433
61653561616166356535623939623065323633663234346635336265346661616237646139303431
64313933396534613563623662373930616532323865373033303937616262306463323465663863
34336463613531313736303830353061626330336138316538323938366361343235343038663462
34653934643531306337363432636631393333623933383930616530333632366235
